services:
  backend:
    container_name: django
    image: django
    build: ./backend
    volumes:
      - ./backend/mysite:/app/mysite
      - media_volume:/app/mysite/media  # mediaディレクトリをボリュームとして定義
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4242:4242"
    networks:
      - app-network
    logging:
      driver: json-file

  # caddy:
  #   container_name: caddy
  #   image: caddy
  #   build:
  #     context: .
  #     dockerfile: caddy/Dockerfile
  #   ports:
  #     - "3000:443"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend

  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    env_file:
      - .env
    ports:
      #- "3000:3000"
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - nginx_ssl:/etc/nginx/ssl
      - media_volume:/usr/share/nginx/html/media  # フロントエンドにmediaディレクトリをマウント
    networks:
      - app-network
    depends_on:
      - backend

  db:
    #image: postgres:13
    container_name: postgres
    image: postgres
    build: ./database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  redis:
    image: "redis:7.2.3-alpine"
    container_name: "redis"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - app-network

volumes:
  media_volume:  # メディアファイル用のボリュームを定義
  postgres_data:
  nginx_ssl:

networks:
  app-network:
    name: ft_transcendence
    driver: bridge
